mybatis-plus:
  check-config-location: false
  executor-type: simple
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl